# Generated by Django 5.2.4 on 2025-08-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
