name: Build and Deploy Backend Container to Azure

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4 # Use latest checkout action

      - name: "Log in to Azure Container Registry"
        uses: docker/login-action@v3 # Use latest login action
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: "Build and push Docker image"~~
        uses: docker/build-push-action@v5 # Use latest build-push action
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/deployment-backend:latest

      - name: "Log in to Azure"
        uses: azure/login@v2 # Use latest Azure login action
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Deploy to Azure App Service"
        uses: azure/webapps-deploy@v3 # Use latest deploy action
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: "${{ secrets.ACR_LOGIN_SERVER }}/deployment-backend:latest"
