name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}
      DEBUG: "False"
      ALLOWED_HOSTS: "luks-backend-app.azurewebsites.net"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies into a local directory
        run: |
          pip install --target="./.python_packages/lib/site-packages" -r requirements.txt

      - name: Run database migrations
        run: |
          # Temporarily add packages to python path to run commands
          export PYTHONPATH="./.python_packages/lib/site-packages"
          python manage.py migrate --noinput

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        with:
          app-name: "luks-backend-app"
          # This action will zip up the code and the .python_packages folder
