name: Build and deploy Python app to Azure Web App - luks-backend-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # We don't need to create a venv or install dependencies here anymore.
      # Azure will do this. We just need to upload the code.

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: . # Upload the entire repository content

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ACE4B85073734234B35000425EFB777F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9E90A18BAEBF4DEB9AE1A77761C2DAB5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2804B47199C346C8BFF67BD2E3027012 }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "luks-backend-app"
          slot-name: "Production"
          package: . # This tells the deploy action to use the downloaded artifact

      # --- THIS IS THE NEW, CRUCIAL STEP ---
      - name: Run post-deployment commands
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set --resource-group LuksRestaurant-RG --name luks-backend-app --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
            az webapp restart --name luks-backend-app --resource-group LuksRestaurant-RG
