name: Build and deploy Python app to Azure Web App - luks-backend-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      DEBUG: "False"
      ALLOWED_HOSTS: "luks-backend-app.azurewebsites.net"
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # We will let Azure handle the venv and pip install.
      # We only install dependencies here to run the manage.py commands.
      - name: Install dependencies for build steps
        run: pip install -r requirements.txt

      # The env variables are available to all steps below
      - name: Run database migrations
        run: python manage.py migrate --noinput

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      # We don't need to upload the venv anymore.
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ACE4B85073734234B35000425EFB777F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9E90A18BAEBF4DEB9AE1A77761C2DAB5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2804B47199C346C8BFF67BD2E3027012 }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "luks-backend-app"
          slot-name: "Production"
