name: Deploy Python app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ACE4B85073734234B35000425EFB777F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9E90A18BAEBF4DEB9AE1A77761C2DAB5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2804B47199C346C8BFF67BD2E3027012 }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        with:
          app-name: "luks-backend-app"
          slot-name: "Production"
